# Generated by Django 5.2.17 on 2026-08-31 15:49

import django.db.models.deletion
from django.db import migrations, models


def rename_operator_to_user(apps, schema_editor):
    Staff = apps.get_model('accounts', 'Staff')
    Staff.objects.filter(role='operator').update(role='user')


def rename_user_to_operator(apps, schema_editor):
    Staff = apps.get_model('accounts', 'Staff')
    Staff.objects.filter(role='user').update(role='operator')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('members', '0002_plan_member_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='member',
            field=models.ForeignKey(blank=True, help_text='ユーザーロールのアカウントが紐付く会員（自分のQR/カードID表示に使用）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_accounts', to='members.member'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('admin', '管理者'), ('user', 'ユーザー')], default='user', max_length=10, verbose_name='権限'),
        ),
        migrations.RunPython(rename_operator_to_user, rename_user_to_operator),
    ]
