# Generated by Django 5.2.17 on 2026-09-01 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_staff_member_alter_staff_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='language',
            field=models.CharField(choices=[('ja', '日本語'), ('en', 'English')], default='ja', max_length=5, verbose_name='表示言語'),
        ),
    ]
