# Generated by Django 5.2.17 on 2026-08-31 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrgSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled_checkin_methods', models.JSONField(default=list, help_text='受付画面で有効化する入力方式コードのリスト（例: ["card","pin","qr"]）', verbose_name='有効な入力方式')),
                ('csv_export_columns', models.JSONField(default=list, help_text='CSVエクスポート時に含める列キーのリスト', verbose_name='CSV出力列')),
            ],
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('url', models.URLField(max_length=500, verbose_name='通知先URL')),
                ('secret', models.CharField(blank=True, max_length=200, verbose_name='シークレット')),
                ('event_types', models.JSONField(default=list, help_text='発火するイベント種別のリスト（checkin / checkout）', verbose_name='発火イベント')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
