# Generated by Django 5.2.17 on 2026-08-27 06:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('check_in', '入室'), ('check_out', '退室')], max_length=10, verbose_name='種別')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='打刻日時')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='members.member')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
