# Generated by Django 5.2.17 on 2026-08-31 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='method',
            field=models.CharField(choices=[('card', 'バーコード/ICカード'), ('pin', '番号入力'), ('qr', 'QRコード'), ('fingerprint', '指紋認証'), ('phone', 'スマホ認証')], default='card', max_length=20, verbose_name='入力方式'),
        ),
    ]
