# Generated by Django 5.2.17 on 2026-08-31 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_accesslog_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='method',
            field=models.CharField(choices=[('card', 'バーコード/ICカード'), ('pin', '番号入力'), ('qr', 'QRコード'), ('fingerprint', '指紋認証'), ('phone', 'スマホ認証'), ('manual', '手動入力（管理者）')], default='card', max_length=20, verbose_name='入力方式'),
        ),
    ]
