# Generated by Django 5.2.17 on 2026-08-27 06:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='会員名')),
                ('company_name', models.CharField(blank=True, max_length=150, verbose_name='所属企業・テナント名')),
                ('card_identifier', models.CharField(help_text='バーコード文字列またはICカードのIDm', max_length=100, unique=True, verbose_name='カードID')),
                ('status', models.CharField(choices=[('active', '有効'), ('inactive', '無効')], default='active', max_length=10, verbose_name='ステータス')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
