# Generated by Django 5.2.17 on 2026-09-05 08:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0004_alter_accesslog_method'),
        ('members', '0002_plan_member_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=50, unique=True, verbose_name='カード番号')),
                ('status', models.CharField(choices=[('available', '在庫'), ('loaned', '貸出中'), ('lost', '紛失'), ('retired', '廃止')], default='available', max_length=10, verbose_name='ステータス')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
            ],
            options={
                'ordering': ['card_number'],
            },
        ),
        migrations.CreateModel(
            name='CardLoan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='貸出日時')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='返却日時')),
                ('access_log_in', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_loan_issued', to='access.accesslog')),
                ('access_log_out', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_loan_returned', to='access.accesslog')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_card_loans', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_loans', to='members.member')),
                ('returned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returned_card_loans', to=settings.AUTH_USER_MODEL)),
                ('security_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='cards.securitycard')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
    ]
